### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by sampathkumar0511** [ulule/django-safety#4]
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/normsoftware/project/sampath/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/normsoftware/project/django-safety-master/safety/models.py", line 14, in <module>
    from . import managers
  File "/home/normsoftware/project/django-safety-master/safety/managers.py", line 6, in <module>
    from . import utils
  File "/home/normsoftware/project/django-safety-master/safety/utils.py", line 4, in <module>
    from .compat import import_module
  File "/home/normsoftware/project/django-safety-master/safety/compat.py", line 13, in <module>
    from django.contrib.gis.geoip import GeoIP as GeoIP  # noqa
ImportError: No module named 'django.contrib.gis.geoip'

**Comment by thoas** [comment]
not an issue, please install geoip packages on your server/computer
